---
- name: Setup MongoDB Config Server
  hosts: ansible_master
  gather_facts: no
  become: yes
  tasks:
    - name: Include MongoDB Config Server Role
      include_role:
        name: mongodb_config_server
