---
- name: Setup AWS Secrets
  hosts: ansible_master
  gather_facts: no
  become: yes
  tasks:
    - name: Retrieve MongoDB Secrets from AWS Secrets Manager
      aws_secret:
        region: us-east-1  
        name: SeronSecrets
      register: SeronSecrets

    - name: Set SeronSecrets as Facts
      set_fact:
        mongodb_username: "{{ SeronSecrets.SecretString.username }}"
        mongodb_password: "{{ SeronSecrets.SecretString.password }}"
